name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            release_name: ComputerUseAgent-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            release_name: ComputerUseAgent-windows
          - os: macos-latest
            target: x86_64-apple-darwin
            release_name: ComputerUseAgent-macos

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build binary
        run: deno compile --allow-all --target ${{ matrix.target }} --output ${{ matrix.release_name }} src/main.ts

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ComputerUseAgent*
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}